### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by DanTulovsky** [rantav/go-grpc-channelz#8]
Hi,

No matter what I try to do, the http response is always "404 page not found".  I tried the included demo in: internal/demo/server/main/main.go.

% go run main.go
demo server is up is up; gRPC bind address: :8080, http admin address: :8081
Hello was successful
Hello was successful
Hello was successful
...

Going to: http://localhost:8081/foo/channelz
Results in: "404 page not found"

Thank you
Dan

**Comment by DanTulovsky** [comment]
Sorry, I managed to my code working.  I am not sure why the included example doesn't work. My problems was incorrect routing by gorilla mux...

**Comment by Lord-Y** [comment]
I can confirm that the demo example doesn't work for me either. Too bad

**Comment by Jille** [comment]
For posterity: It took me a while to realize that the trailing slash is required in the request URL. So http://localhost:8081/foo/channelz/ ought to have worked.
